# Generated by Django 4.0.6 on 2024-09-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sams', '0005_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
